server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: Stock
          uri: http://localhost:8082
          predicates:
            - Path=/stocks/** 
        - id: StockManagement
          uri: http://localhost:8083
          predicates:
            - Path=/stockManagements/** 
        - id: Board
          uri: http://localhost:8084
          predicates:
            - Path= /boards/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://Order:8080
          predicates:
            - Path=/orders/** 
        - id: Stock
          uri: http://Stock:8080
          predicates:
            - Path=/stocks/** 
        - id: StockManagement
          uri: http://StockManagement:8080
          predicates:
            - Path=/stockManagements/** 
        - id: Board
          uri: http://Board:8080
          predicates:
            - Path= /boards/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
